<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-11-22T13:07:41Z" name="Default suite" finished-at="2022-11-22T13:07:56Z" duration-ms="14716">
    <groups>
    </groups>
    <test started-at="2022-11-22T13:07:41Z" name="Default test" finished-at="2022-11-22T13:07:56Z" duration-ms="14716">
      <class name="com.example.demo.CapstoneHomepageTest">
        <test-method signature="loginTest()[pri:0, instance:com.example.demo.CapstoneHomepageTest@4f0100a7]" started-at="2022-11-22T13:07:41Z" name="loginTest" finished-at="2022-11-22T13:07:51Z" duration-ms="10052" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test This DashboardsURL expected [http://localhost:3000/login] but found [http://localhost:3000/dashboards]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test This DashboardsURL expected [http://localhost:3000/login] but found [http://localhost:3000/dashboards]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.example.demo.CapstoneHomepageTest.loginTest(CapstoneHomepageTest.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method signature="navigateToHomepage()[pri:0, instance:com.example.demo.CapstoneHomepageTest@4f0100a7]" started-at="2022-11-22T13:07:51Z" name="navigateToHomepage" finished-at="2022-11-22T13:07:56Z" duration-ms="4598" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateToHomepage -->
      </class> <!-- com.example.demo.CapstoneHomepageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
